package models;

import play.data.validation.Constraints.Required;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="journwe-adventure")
public class Adventure {

	private String inspirationId;
	
	private String id;
	
	@Required
	private String name;

	/**
	 * @return the inspirationId
	 */
	@DynamoDBHashKey(attributeName="inspirationId")
	public String getInspirationId() {
		return inspirationId;
	}

	/**
	 * @param inspirationId the inspirationId to set
	 */
	public void setInspirationId(String inspirationId) {
		this.inspirationId = inspirationId;
	}

	/**
	 * @return the id
	 */
	@DynamoDBRangeKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	
	
}
