package models;

import play.data.validation.Constraints.Required;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="journwe-adventure")
public class Adventure {

	private String inspirationId;
	
	private String id;
	
	@Required
	private String name;
	
	private boolean publish = false;
	
	private boolean limited = false;
	
	private Integer limit;

	/**
	 * @return the inspirationId
	 */
	@DynamoDBHashKey(attributeName="inspirationId")
	public String getInspirationId() {
		return inspirationId;
	}

	/**
	 * @param inspirationId the inspirationId to set
	 */
	public void setInspirationId(String inspirationId) {
		this.inspirationId = inspirationId;
	}

	/**
	 * @return the id
	 */
	@DynamoDBRangeKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	@DynamoDBAttribute
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the publish
	 */
	@DynamoDBAttribute
	public boolean isPublish() {
		return publish;
	}

	/**
	 * @param publish the publish to set
	 */
	public void setPublish(boolean publish) {
		this.publish = publish;
	}

	/**
	 * @return the limited
	 */
	@DynamoDBAttribute
	public boolean isLimited() {
		return limited;
	}

	/**
	 * @param limited the limited to set
	 */
	public void setLimited(boolean limited) {
		this.limited = limited;
	}

	/**
	 * @return the limit
	 */
	@DynamoDBAttribute
	public Integer getLimit() {
		return limit;
	}

	/**
	 * @param limit the limit to set
	 */
	public void setLimit(Integer limit) {
		this.limit = limit;
	}
	
	
	
}
