package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import play.data.validation.Constraints.Required;

/**
 * The comment model with range key = threadId and secondary index = timestamp.
 *
 * @author markus
 */
@DynamoDBTable(tableName = "journwe-comment")
public class Comment {

    private String commentId;

    @Required
    private Long timestamp;

    @Required
    private String commentThreadId;

    @Required
    private String userId;

    @Required
    private String text;


    /**
     * @return the id
     */
    @DynamoDBHashKey(attributeName = "commentId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return commentId;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.commentId = id;
    }

    @DynamoDBRangeKey(attributeName = "commentThreadId")
    @DynamoDBAttribute
    public String getCommentThreadId() {
        return commentThreadId;
    }

    public void setCommentThreadId(String commentThreadId) {
        this.commentThreadId = commentThreadId;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBIndexRangeKey(localSecondaryIndexName = "timestamp-index", attributeName = "timestamp")
    @DynamoDBAttribute
    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long time) {
        this.timestamp = time;
    }

    @DynamoDBAttribute
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

}
