package models;

import play.data.validation.Constraints.Required;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * The comment model with range key = threadId and secondary index = timestamp.
 * 
 * @author markus
 *
 */
@DynamoDBTable(tableName="journwe-comment")
public class Comment {

	private String commentId;
	
	@Required
	private Long timestamp;

	@Required
	private String commentThreadId;
	
	@Required
	private String userId;
	
	@Required
	private String text;
	
	
	/**
	 * @return the id
	 */
	@DynamoDBHashKey(attributeName = "commentId")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return commentId;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.commentId = id;
	}

	@DynamoDBRangeKey(attributeName = "commentThreadId")
	@DynamoDBAttribute
	protected String getCommentThreadId() {
		return commentThreadId;
	}

	protected void setCommentThreadId(String commentThreadId) {
		this.commentThreadId = commentThreadId;
	}

	@DynamoDBAttribute
	protected String getUserId() {
		return userId;
	}

	protected void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBIndexRangeKey(attributeName = "timestamp")
	@DynamoDBAttribute
	protected Long getTimestamp() {
		return timestamp;
	}

	protected void setTimestamp(Long time) {
		this.timestamp = time;
	}

	@DynamoDBAttribute
	protected String getText() {
		return text;
	}

	protected void setText(String text) {
		this.text = text;
	}

}
