package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import models.helpers.WeatherFactory;
import play.data.validation.Constraints.Required;

@DynamoDBTable(tableName = "journwe-inspiration")
public class Inspiration {

    private String inspirationId;

    private String categoryId;

    @Required
    private String name;

    private String description;

    private String image;

    private String tripAdvisor;

    private String pinterest;

    private String weatherId;

    /**
     * @return the categoryId
     */
    @DynamoDBHashKey(attributeName = "categoryId")
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * @return the inspirationId
     */
    @DynamoDBRangeKey(attributeName = "inspirationId")
    @DynamoDBAutoGeneratedKey
    public String getInspirationId() {
        return inspirationId;
    }

    /**
     * @param inspirationId the inspirationId to set
     */
    public void setInspirationId(String inspirationId) {
        this.inspirationId = inspirationId;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the description
     */
    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getTripAdvisor() {
        return tripAdvisor;
    }

    /**
     * @param ta Provides a snipped for trip advisor
     */
    public void setTripAdvisor(String ta) {
        this.tripAdvisor = ta;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getPinterest() {
        return pinterest;
    }

    /**
     * @param pinterest Provides a snipped for trip advisor
     */
    public void setPinterest(String pinterest) {
        this.pinterest = pinterest;
    }

    /**
     *
     */
    @DynamoDBIgnore
    public Weather getWeather() {
        if (this.weatherId == null){
            return null;
        }
        return WeatherFactory.getWeather(this.weatherId);
    }

    /**
     *
     */
    @DynamoDBAttribute
    public String getWeatherId() {
        return this.weatherId;
    }

    /**
     *
     */
    public void setWeatherId(String weatherId) {
        this.weatherId = weatherId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Inspiration [categoryId=" + categoryId
                + ", inspirationId=" + inspirationId + ", name=" + name + ", description="
                + description + ", image=" + image + "]";
    }


}
