package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import models.helpers.WeatherFactory;
import play.data.validation.Constraints.Required;

@DynamoDBTable(tableName = "journwe-inspiration")
public class Inspiration {

    private String id;

    private String inspirationCategoryId;

    @Required
    private String name;

    private String description;

    private String image;

    private String tripAdvisor;

    private String pinterest;

    private String weatherId;

    /**
     * @return the inspirationCategoryId
     */
    @DynamoDBAttribute(attributeName = "inspirationCategoryId")
    public String getInspirationCategoryId() {
        return inspirationCategoryId;
    }

    /**
     * @param inspirationCategoryId the inspirationCategoryId to set
     */
    public void setInspirationCategoryId(String inspirationCategoryId) {
        this.inspirationCategoryId = inspirationCategoryId;
    }

    /**
     * @return the id
     */
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the description
     */
    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getImage() {
        return image;
    }

    /**
     * @param image the image to set
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getTripAdvisor() {
        return tripAdvisor;
    }

    /**
     * @param ta Provides a snipped for trip advisor
     */
    public void setTripAdvisor(String ta) {
        this.tripAdvisor = ta;
    }

    /**
     * @return the image
     */
    @DynamoDBAttribute
    public String getPinterest() {
        return pinterest;
    }

    /**
     * @param pinterest Provides a snipped for trip advisor
     */
    public void setPinterest(String pinterest) {
        this.pinterest = pinterest;
    }

    /**
     *
     */
    @DynamoDBIgnore
    public Weather getWeather() {
        if (this.weatherId == null){
            return null;
        }
        return WeatherFactory.getWeather(this.weatherId);
    }

    /**
     *
     */
    @DynamoDBAttribute
    public String getWeatherId() {
        return this.weatherId;
    }

    /**
     *
     */
    public void setWeatherId(String weatherId) {
        this.weatherId = weatherId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "Inspiration [inspirationCategoryId=" + inspirationCategoryId
                + ", id=" + id + ", name=" + name + ", description="
                + description + ", image=" + image + "]";
    }


}
