package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ecwid.mailchimp.MailChimpClient;
import com.ecwid.mailchimp.MailChimpException;
import com.ecwid.mailchimp.method.list.ListSubscribeMethod;
import com.feth.play.module.pa.user.AuthUser;
import com.feth.play.module.pa.user.AuthUserIdentity;
import com.feth.play.module.pa.user.EmailIdentity;
import com.feth.play.module.pa.user.NameIdentity;
import models.dao.SubscriberDAO;
import models.dao.UserDAO;
import models.dao.UserEmailDAO;
import models.dao.UserSocialDAO;
import models.helpers.EnumMarshaller;
import play.data.validation.Constraints.Required;

import java.io.IOException;

@DynamoDBTable(tableName = "journwe-user")
public class User {

    private String id;

    @Required
    private String name;

    private boolean active;

    private EUserRole role = EUserRole.USER;

    /**
     * @return the id
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the active
     */
    @DynamoDBAttribute
    public boolean getActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * @return the role
     */
    @DynamoDBMarshalling(marshallerClass = UserRoleMarshaller.class)
    public EUserRole getRole() {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(EUserRole role) {
        this.role = role;
    }

    /**
     * public static final Finder<Long, User> find = new Finder<Long, User>(
     * Long.class, User.class);
     */

    public static boolean existsByAuthUserIdentity(
            final AuthUserIdentity identity) {
        return getAuthUserFind(identity) != null;
    }

    private static User getAuthUserFind(final AuthUserIdentity identity) {
        UserSocial social = new UserSocialDAO().get(identity.getProvider(), identity.getId());
        return social != null ? new UserDAO().get(social.getUserId()) : null;
    }

    public static User findByAuthUserIdentity(final AuthUserIdentity identity) {
        if (identity == null)
            return null;

        return getAuthUserFind(identity);
    }

    public static User create(final AuthUser authUser) {
        final User user = new User();
        user.setActive(true);
        if (authUser instanceof NameIdentity) {
            final NameIdentity identity = (NameIdentity) authUser;
            final String name = identity.getName();
            if (name != null) {
                user.setName(name);
            }
        }
        new UserDAO().save(user);


        if (authUser instanceof EmailIdentity) {
            final UserEmail email = new UserEmail();
            email.setUserId(user.getId());

            final EmailIdentity identity = (EmailIdentity) authUser;
            // Remember, even when getting them from FB & Co., emails should be
            // verified within the application as a security breach there might
            // break your security as well!
            email.setEmail(identity.getEmail());
            email.setValidated(false);
            email.setPrimary(true);
            new UserEmailDAO().save(email);

            Subscriber sub = new Subscriber();
            sub.setEmail(email.getEmail());
            new SubscriberDAO().save(sub);
            try {
                ListSubscribeMethod listSubscribeMethod = new ListSubscribeMethod();
                listSubscribeMethod.apikey = "426c4fc75113db8416df74f92831d066-us4";
                listSubscribeMethod.id = "c18d5a32fb";
                listSubscribeMethod.email_address = sub.getEmail();
                listSubscribeMethod.double_optin = false;
                listSubscribeMethod.update_existing = true;
                listSubscribeMethod.send_welcome = true;

                new MailChimpClient().execute(listSubscribeMethod);
            } catch (IOException e) {
                e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
            } catch (MailChimpException e) {
                e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
            }

        }

        final UserSocial social = new UserSocial();
        social.setProvider(authUser.getProvider());
        social.setSocialId(authUser.getId());
        social.setUserId(user.getId());
        new UserSocialDAO().save(social);

        return user;
    }

    public static class UserRoleMarshaller extends EnumMarshaller<EUserRole> {
    }

}
