package models.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ecwid.mailchimp.MailChimpClient;
import com.ecwid.mailchimp.MailChimpException;
import com.ecwid.mailchimp.method.list.ListSubscribeMethod;
import com.feth.play.module.pa.user.AuthUser;
import com.feth.play.module.pa.user.AuthUserIdentity;
import com.feth.play.module.pa.user.EmailIdentity;
import com.feth.play.module.pa.user.NameIdentity;
import models.dao.SubscriberDAO;
import models.dao.UserDAO;
import models.dao.UserEmailDAO;
import models.dao.UserSocialDAO;
import models.helpers.EnumMarshaller;
import play.data.validation.Constraints.Required;

import java.io.IOException;

@DynamoDBTable(tableName = "journwe-user")
public class User {

    private String id;

    @Required
    private String name;

    private boolean active;

    private EUserRole role = EUserRole.USER;

    /**
     * @return the id
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the active
     */
    @DynamoDBAttribute
    public boolean getActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * @return the role
     */
    @DynamoDBMarshalling(marshallerClass = UserRoleMarshaller.class)
    public EUserRole getRole() {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(EUserRole role) {
        this.role = role;
    }

    public static class UserRoleMarshaller extends EnumMarshaller<EUserRole> {
    }

}
