package models.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.ecwid.mailchimp.MailChimpClient;
import com.ecwid.mailchimp.MailChimpException;
import com.ecwid.mailchimp.method.list.ListSubscribeMethod;
import com.feth.play.module.pa.user.AuthUser;
import com.feth.play.module.pa.user.AuthUserIdentity;
import com.feth.play.module.pa.user.EmailIdentity;
import com.feth.play.module.pa.user.NameIdentity;
import models.dao.SubscriberDAO;
import models.dao.UserDAO;
import models.dao.UserEmailDAO;
import models.dao.UserSocialDAO;
import models.helpers.EnumMarshaller;
import models.notifications.ENotificationFrequency;
import play.data.validation.Constraints.Required;

import java.io.IOException;
import java.util.Date;

@DynamoDBTable(tableName = "journwe-user")
public class User {

    private String id;

    @Required
    private String name;

    private String image;

    private boolean active;

    private EUserRole role = EUserRole.USER;

    private ENotificationFrequency notificationDigest = ENotificationFrequency.IMMEDIATELY;

    private Date lastDigest = new Date();

    /**
     * @return the id
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }


    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    /**
     * @return the active
     */
    @DynamoDBAttribute
    public boolean getActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * @return the role
     */
    @DynamoDBMarshalling(marshallerClass = UserRoleMarshaller.class)
    public EUserRole getRole() {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(EUserRole role) {
        this.role = role;
    }

    @DynamoDBMarshalling(marshallerClass = NotificationFrequencyMarshaller.class)
    public ENotificationFrequency getNotificationDigest() {
        return notificationDigest;
    }

    public void setNotificationDigest(ENotificationFrequency notificationDigest) {
        this.notificationDigest = notificationDigest;
    }

    @DynamoDBAttribute
    public Date getLastDigest() {
        return lastDigest;
    }

    public void setLastDigest(Date lastDigest) {
        this.lastDigest = lastDigest;
    }

    public static class UserRoleMarshaller extends EnumMarshaller<EUserRole> {
    }

    public static class NotificationFrequencyMarshaller extends EnumMarshaller<ENotificationFrequency> {
    }

}
