package com.journwe.flight.skyscanner.model.reference;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map.Entry;
import java.util.Set;

public class Countries {

	private static HashMap<String,Country> countryMap = new HashMap<String,Country>();

	static{
		countryMap.put("Afghanistan", new Country("Afghanistan","AF"));
		countryMap.put("Albania", new Country("Albania","AL"));
		countryMap.put("Algeria", new Country("Algeria","DZ"));
		countryMap.put("American Samoa", new Country("American Samoa","AS"));
		countryMap.put("Angola", new Country("Angola","AO"));
		countryMap.put("Anguilla", new Country("Anguilla","AI"));
		countryMap.put("Antarctica", new Country("Antarctica","AQ"));
		countryMap.put("Antigua and Barbuda", new Country("Antigua and Barbuda","AG"));
		countryMap.put("Argentina", new Country("Argentina","AR"));
		countryMap.put("Armenia", new Country("Armenia","AM"));
		countryMap.put("Aruba", new Country("Aruba","AW"));
		countryMap.put("Australia", new Country("Australia","AU"));
		countryMap.put("Austria", new Country("Austria","AT"));
		countryMap.put("Azerbaijan", new Country("Azerbaijan","AZ"));
		countryMap.put("Bahamas", new Country("Bahamas","BS"));
		countryMap.put("Bahrain", new Country("Bahrain","BH"));
		countryMap.put("Bangladesh", new Country("Bangladesh","BD"));
		countryMap.put("Barbados", new Country("Barbados","BB"));
		countryMap.put("Belarus", new Country("Belarus","BY"));
		countryMap.put("Belgium", new Country("Belgium","BE"));
		countryMap.put("Belize", new Country("Belize","BZ"));
		countryMap.put("Benin", new Country("Benin","BJ"));
		countryMap.put("Bermuda", new Country("Bermuda","BM"));
		countryMap.put("Bhutan", new Country("Bhutan","BT"));
		countryMap.put("Bolivia", new Country("Bolivia","BO"));
		countryMap.put("Bosnia and Herzegovina", new Country("Bosnia and Herzegovina","BA"));
		countryMap.put("Botswana", new Country("Botswana","BW"));
		countryMap.put("Brazil", new Country("Brazil","BR"));
		countryMap.put("British Virgin Islands", new Country("British Virgin Islands","VG"));
		countryMap.put("Brunei", new Country("Brunei","BN"));
		countryMap.put("Bulgaria", new Country("Bulgaria","BG"));
		countryMap.put("Burkina Faso", new Country("Burkina Faso","BF"));
		countryMap.put("Burundi", new Country("Burundi","BI"));
		countryMap.put("Cambodia", new Country("Cambodia","KH"));
		countryMap.put("Cameroon", new Country("Cameroon","CM"));
		countryMap.put("Canada", new Country("Canada","CA"));
		countryMap.put("Cape Verde", new Country("Cape Verde","CV"));
		countryMap.put("Caribbean Netherlands", new Country("Caribbean Netherlands","BQ"));
		countryMap.put("Cayman Islands", new Country("Cayman Islands","KY"));
		countryMap.put("Central African Republic", new Country("Central African Republic","CF"));
		countryMap.put("Chad", new Country("Chad","TD"));
		countryMap.put("Chile", new Country("Chile","CL"));
		countryMap.put("China", new Country("China","CN"));
		countryMap.put("Christmas Island", new Country("Christmas Island","CX"));
		countryMap.put("Cocos (Keeling) Islands", new Country("Cocos (Keeling) Islands","CC"));
		countryMap.put("Colombia", new Country("Colombia","CO"));
		countryMap.put("Comoros", new Country("Comoros","KM"));
		countryMap.put("Congo", new Country("Congo","CG"));
		countryMap.put("Cook Islands", new Country("Cook Islands","CK"));
		countryMap.put("Costa Rica", new Country("Costa Rica","CR"));
		countryMap.put("Croatia", new Country("Croatia","HR"));
		countryMap.put("Cuba", new Country("Cuba","CU"));
		countryMap.put("Curacao", new Country("Curacao","CW"));
		countryMap.put("Cyprus", new Country("Cyprus","CY"));
		countryMap.put("Czech Republic", new Country("Czech Republic","CZ"));
		countryMap.put("Denmark", new Country("Denmark","DK"));
		countryMap.put("Djibouti", new Country("Djibouti","DJ"));
		countryMap.put("Dominica", new Country("Dominica","DM"));
		countryMap.put("Dominican Republic", new Country("Dominican Republic","DO"));
		countryMap.put("DR Congo", new Country("DR Congo","CD"));
		countryMap.put("East Timor", new Country("East Timor","TL"));
		countryMap.put("Ecuador", new Country("Ecuador","EC"));
		countryMap.put("Egypt", new Country("Egypt","EG"));
		countryMap.put("El Salvador", new Country("El Salvador","SV"));
		countryMap.put("Equatorial Guinea", new Country("Equatorial Guinea","GQ"));
		countryMap.put("Eritrea", new Country("Eritrea","ER"));
		countryMap.put("Estonia", new Country("Estonia","EE"));
		countryMap.put("Ethiopia", new Country("Ethiopia","ET"));
		countryMap.put("Falkland Islands", new Country("Falkland Islands","FK"));
		countryMap.put("Faroe Islands", new Country("Faroe Islands","FO"));
		countryMap.put("Fiji", new Country("Fiji","FJ"));
		countryMap.put("Finland", new Country("Finland","FI"));
		countryMap.put("France", new Country("France","FR"));
		countryMap.put("French Guiana", new Country("French Guiana","GF"));
		countryMap.put("French Polynesia", new Country("French Polynesia","PF"));
		countryMap.put("Gabon", new Country("Gabon","GA"));
		countryMap.put("Gambia", new Country("Gambia","GM"));
		countryMap.put("Georgia", new Country("Georgia","GE"));
		countryMap.put("Germany", new Country("Germany","DE"));
		countryMap.put("Ghana", new Country("Ghana","GH"));
		countryMap.put("Gibraltar", new Country("Gibraltar","GI"));
		countryMap.put("Greece", new Country("Greece","GR"));
		countryMap.put("Greenland", new Country("Greenland","GL"));
		countryMap.put("Grenada", new Country("Grenada","GD"));
		countryMap.put("Guadeloupe", new Country("Guadeloupe","GP"));
		countryMap.put("Guam", new Country("Guam","GU"));
		countryMap.put("Guatemala", new Country("Guatemala","GT"));
		countryMap.put("Guernsey", new Country("Guernsey","GG"));
		countryMap.put("Guinea", new Country("Guinea","GN"));
		countryMap.put("Guinea-Bissau", new Country("Guinea-Bissau","GW"));
		countryMap.put("Guyana", new Country("Guyana","GY"));
		countryMap.put("Haiti", new Country("Haiti","HT"));
		countryMap.put("Honduras", new Country("Honduras","HN"));
		countryMap.put("Hong Kong", new Country("Hong Kong","HK"));
		countryMap.put("Hungary", new Country("Hungary","HU"));
		countryMap.put("Iceland", new Country("Iceland","IS"));
		countryMap.put("India", new Country("India","IN"));
		countryMap.put("Indonesia", new Country("Indonesia","ID"));
		countryMap.put("Iran", new Country("Iran","IR"));
		countryMap.put("Iraq", new Country("Iraq","IQ"));
		countryMap.put("Ireland", new Country("Ireland","IE"));
		countryMap.put("Israel", new Country("Israel","IL"));
		countryMap.put("Italy", new Country("Italy","IT"));
		countryMap.put("Ivory Coast", new Country("Ivory Coast","CI"));
		countryMap.put("Jamaica", new Country("Jamaica","JM"));
		countryMap.put("Japan", new Country("Japan","JP"));
		countryMap.put("Jordan", new Country("Jordan","JO"));
		countryMap.put("Kazakhstan", new Country("Kazakhstan","KZ"));
		countryMap.put("Kenya", new Country("Kenya","KE"));
		countryMap.put("Kiribati", new Country("Kiribati","KI"));
		countryMap.put("Kosovo", new Country("Kosovo","KO"));
		countryMap.put("Kuwait", new Country("Kuwait","KW"));
		countryMap.put("Kyrgyzstan", new Country("Kyrgyzstan","KG"));
		countryMap.put("Laos", new Country("Laos","LA"));
		countryMap.put("Latvia", new Country("Latvia","LV"));
		countryMap.put("Lebanon", new Country("Lebanon","LB"));
		countryMap.put("Lesotho", new Country("Lesotho","LS"));
		countryMap.put("Liberia", new Country("Liberia","LR"));
		countryMap.put("Libya", new Country("Libya","LY"));
		countryMap.put("Lithuania", new Country("Lithuania","LT"));
		countryMap.put("Luxembourg", new Country("Luxembourg","LU"));
		countryMap.put("Macau", new Country("Macau","MO"));
		countryMap.put("Madagascar", new Country("Madagascar","MG"));
		countryMap.put("Malawi", new Country("Malawi","MW"));
		countryMap.put("Malaysia", new Country("Malaysia","MY"));
		countryMap.put("Maldives", new Country("Maldives","MV"));
		countryMap.put("Mali", new Country("Mali","ML"));
		countryMap.put("Malta", new Country("Malta","MT"));
		countryMap.put("Marshall Islands", new Country("Marshall Islands","MH"));
		countryMap.put("Martinique", new Country("Martinique","MQ"));
		countryMap.put("Mauritania", new Country("Mauritania","MR"));
		countryMap.put("Mauritius", new Country("Mauritius","MU"));
		countryMap.put("Mayotte", new Country("Mayotte","YT"));
		countryMap.put("Mexico", new Country("Mexico","MX"));
		countryMap.put("Micronesia", new Country("Micronesia","FM"));
		countryMap.put("Moldova", new Country("Moldova","MD"));
		countryMap.put("Monaco", new Country("Monaco","MC"));
		countryMap.put("Mongolia", new Country("Mongolia","MN"));
		countryMap.put("Montenegro", new Country("Montenegro","ME"));
		countryMap.put("Montserrat", new Country("Montserrat","MS"));
		countryMap.put("Morocco", new Country("Morocco","MA"));
		countryMap.put("Mozambique", new Country("Mozambique","MZ"));
		countryMap.put("Myanmar", new Country("Myanmar","MM"));
		countryMap.put("Namibia", new Country("Namibia","NA"));
		countryMap.put("Nauru", new Country("Nauru","NR"));
		countryMap.put("Nepal", new Country("Nepal","NP"));
		countryMap.put("Netherlands", new Country("Netherlands","NL"));
		countryMap.put("New Caledonia", new Country("New Caledonia","NC"));
		countryMap.put("New Zealand", new Country("New Zealand","NZ"));
		countryMap.put("Nicaragua", new Country("Nicaragua","NI"));
		countryMap.put("Niger", new Country("Niger","NE"));
		countryMap.put("Nigeria", new Country("Nigeria","NG"));
		countryMap.put("Niue", new Country("Niue","NU"));
		countryMap.put("North Korea", new Country("North Korea","KP"));
		countryMap.put("Northern Mariana Islands", new Country("Northern Mariana Islands","MP"));
		countryMap.put("Norway", new Country("Norway","NO"));
		countryMap.put("Oman", new Country("Oman","OM"));
		countryMap.put("Pakistan", new Country("Pakistan","PK"));
		countryMap.put("Palau", new Country("Palau","PW"));
		countryMap.put("Panama", new Country("Panama","PA"));
		countryMap.put("Papua New Guinea", new Country("Papua New Guinea","PG"));
		countryMap.put("Paraguay", new Country("Paraguay","PY"));
		countryMap.put("Peru", new Country("Peru","PE"));
		countryMap.put("Philippines", new Country("Philippines","PH"));
		countryMap.put("Poland", new Country("Poland","PL"));
		countryMap.put("Portugal", new Country("Portugal","PT"));
		countryMap.put("Puerto Rico", new Country("Puerto Rico","PR"));
		countryMap.put("Qatar", new Country("Qatar","QA"));
		countryMap.put("Republic of Macedonia", new Country("Republic of Macedonia","MK"));
		countryMap.put("Reunion", new Country("Reunion","RE"));
		countryMap.put("Romania", new Country("Romania","RO"));
		countryMap.put("Russia", new Country("Russia","RU"));
		countryMap.put("Rwanda", new Country("Rwanda","RW"));
		countryMap.put("Saint Barthelemy", new Country("Saint Barthelemy","BL"));
		countryMap.put("Saint Kitts and Nevis", new Country("Saint Kitts and Nevis","KN"));
		countryMap.put("Saint Lucia", new Country("Saint Lucia","LC"));
		countryMap.put("Saint Vincent and the Grenadines", new Country("Saint Vincent and the Grenadines","VC"));
		countryMap.put("Samoa", new Country("Samoa","WS"));
		countryMap.put("Sao Tome and Principe", new Country("Sao Tome and Principe","ST"));
		countryMap.put("Saudi Arabia", new Country("Saudi Arabia","SA"));
		countryMap.put("Senegal", new Country("Senegal","SN"));
		countryMap.put("Serbia", new Country("Serbia","RS"));
		countryMap.put("Seychelles", new Country("Seychelles","SC"));
		countryMap.put("Sierra Leone", new Country("Sierra Leone","SL"));
		countryMap.put("Singapore", new Country("Singapore","SG"));
		countryMap.put("Slovakia", new Country("Slovakia","SK"));
		countryMap.put("Slovenia", new Country("Slovenia","SI"));
		countryMap.put("Solomon Islands", new Country("Solomon Islands","SB"));
		countryMap.put("Somalia", new Country("Somalia","SO"));
		countryMap.put("South Africa", new Country("South Africa","ZA"));
		countryMap.put("South Korea", new Country("South Korea","KR"));
		countryMap.put("South Sudan", new Country("South Sudan","SS"));
		countryMap.put("Spain", new Country("Spain","ES"));
		countryMap.put("Sri Lanka", new Country("Sri Lanka","LK"));
		countryMap.put("St Maarten", new Country("St Maarten","SX"));
		countryMap.put("St. Pierre and Miquelon", new Country("St. Pierre and Miquelon","PM"));
		countryMap.put("Sudan", new Country("Sudan","SD"));
		countryMap.put("Suriname", new Country("Suriname","SR"));
		countryMap.put("Swaziland", new Country("Swaziland","SZ"));
		countryMap.put("Sweden", new Country("Sweden","SE"));
		countryMap.put("Switzerland", new Country("Switzerland","CH"));
		countryMap.put("Syria", new Country("Syria","SY"));
		countryMap.put("Taiwan", new Country("Taiwan","TW"));
		countryMap.put("Tajikistan", new Country("Tajikistan","TJ"));
		countryMap.put("Tanzania", new Country("Tanzania","TZ"));
		countryMap.put("Thailand", new Country("Thailand","TH"));
		countryMap.put("Togo", new Country("Togo","TG"));
		countryMap.put("Tonga", new Country("Tonga","TO"));
		countryMap.put("Trinidad and Tobago", new Country("Trinidad and Tobago","TT"));
		countryMap.put("Tunisia", new Country("Tunisia","TN"));
		countryMap.put("Turkey", new Country("Turkey","TR"));
		countryMap.put("Turkmenistan", new Country("Turkmenistan","TM"));
		countryMap.put("Turks and Caicos Islands", new Country("Turks and Caicos Islands","TC"));
		countryMap.put("Tuvalu", new Country("Tuvalu","TV"));
		countryMap.put("Uganda", new Country("Uganda","UG"));
		countryMap.put("Ukraine", new Country("Ukraine","UA"));
		countryMap.put("United Arab Emirates", new Country("United Arab Emirates","AE"));
		countryMap.put("United Kingdom", new Country("United Kingdom","UK"));
		countryMap.put("United States", new Country("United States","US"));
		countryMap.put("Uruguay", new Country("Uruguay","UY"));
		countryMap.put("Uzbekistan", new Country("Uzbekistan","UZ"));
		countryMap.put("Vanuatu", new Country("Vanuatu","VU"));
		countryMap.put("Venezuela", new Country("Venezuela","VE"));
		countryMap.put("Vietnam", new Country("Vietnam","VN"));
		countryMap.put("Virgin Islands", new Country("Virgin Islands","VI"));
		countryMap.put("Wallis and Futuna Islands", new Country("Wallis and Futuna Islands","WF"));
		countryMap.put("Yemen", new Country("Yemen","YE"));
		countryMap.put("Zambia", new Country("Zambia","ZM"));
		countryMap.put("Zimbabwe", new Country("Zimbabwe","ZW"));
	}

	public Set<Entry<String, Country>> entrySet() {
		return countryMap.entrySet();
	}

	public Country get(String key) {
		return countryMap.get(key);
	}

	public Collection<Country> values() {
		return countryMap.values();
	}
	
	
}
