package models.category;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import play.data.validation.Constraints.Required;

@DynamoDBTable(tableName = "journwe-category")
public class Category {

    private String id;

    @Required
    private String name;

    private String image;

    private String description;

    public static final String SUPER_CATEGORY = "SUPER";

    /**
     * @return the id
     */
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBIgnore
    public String getHTMLDescription(){
        return description == null ? "" : description.replaceAll("\n", "<br/>");
    }


    public void setDescription(String description) {
        this.description = description;
    }

    public String validate() {
        if (name == null || "".equals(name)) {
            return "Name required!";
        }
        return null;
    }

}
