package models.user;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import models.dao.helpers.EnumMarshaller;
import models.notifications.ENotificationFrequency;
import play.data.validation.Constraints.Required;
import play.i18n.Lang;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "journwe-user")
public class User implements Serializable {

    private String id;

    @Required
    private String name;

    private String image;

    private boolean active;

    private String hashedPassword;

    private EUserRole role = EUserRole.USER;

    private ENotificationFrequency notificationDigest = ENotificationFrequency.DAILY;

    private Date lastDigest = new Date();

    private Lang language;

    /**
     * @return the id
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the name
     */
    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }


    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    /**
     * @return the active
     */
    @DynamoDBAttribute
    public boolean getActive() {
        return active;
    }

    /**
     * @param active the active to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * @return the role
     */
    @DynamoDBMarshalling(marshallerClass = UserRoleMarshaller.class)
    public EUserRole getRole() {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(EUserRole role) {
        this.role = role;
    }

    @DynamoDBMarshalling(marshallerClass = NotificationFrequencyMarshaller.class)
    public ENotificationFrequency getNotificationDigest() {
        return notificationDigest;
    }

    public void setNotificationDigest(ENotificationFrequency notificationDigest) {
        this.notificationDigest = notificationDigest;
    }

    @DynamoDBAttribute
    public Date getLastDigest() {
        return lastDigest;
    }

    public void setLastDigest(Date lastDigest) {
        this.lastDigest = lastDigest;
    }

    @DynamoDBAttribute
    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    @DynamoDBMarshalling(marshallerClass = LangMarshaller.class)
    public Lang getLanguage() {
        return language;
    }

    public void setLanguage(Lang language) {
        this.language = language;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User user = (User) o;

        if (id != null ? !id.equals(user.id) : user.id != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    public static class UserRoleMarshaller extends EnumMarshaller<EUserRole> {
    }

    public static class NotificationFrequencyMarshaller extends EnumMarshaller<ENotificationFrequency> {
    }

    public static class LangMarshaller implements DynamoDBMarshaller<Lang> {

        @Override
        public String marshall(Lang getterReturnResult) {
            return getterReturnResult.code();
        }

        @Override
        public Lang unmarshall(Class<Lang> clazz, String code) {
            return new Lang(play.api.i18n.Lang.apply(code));
        }
    }

}
