package models.adventure.place;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Created with IntelliJ IDEA.
 * User: mugglmenzel
 * Date: 22.06.13
 * Time: 11:08
 * To change this template use File | Settings | File Templates.
 */
@DynamoDBTable(tableName = "journwe-placeoption")
public class PlaceOption {

    private String id;

    private String adventureId;

    private String name;

    private String description;

    private String googleMapsAddress;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getAdventureId() {
        return adventureId;
    }

    public void setAdventureId(String adventureId) {
        this.adventureId = adventureId;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getGoogleMapsAddress() {
        return googleMapsAddress;
    }

    public void setGoogleMapsAddress(String googleMapsAddress) {
        this.googleMapsAddress = googleMapsAddress;
    }
}
