package models.adventure.checklist;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import play.data.validation.Constraints.Required;

@DynamoDBTable(tableName = "journwe-checklist")
public class Checklist {

	// primary hash key
    private String checklistId;

    @Required
    private String checklistOption;

    @DynamoDBHashKey(attributeName = "checklistId")
    @DynamoDBAutoGeneratedKey
	public String getChecklistId() {
		return checklistId;
	}

	public void setChecklistId(String checklistId) {
		this.checklistId = checklistId;
	}

	@DynamoDBAttribute
	public String getChecklistOption() {
		return checklistOption;
	}

	public void setChecklistOption(String checklistOption) {
		this.checklistOption = checklistOption;
	}

}
