package models.adventure.route;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import models.adventure.IAdventureComponent;
import models.adventure.JournweCloneable;

/**
 * Created with IntelliJ IDEA.
 * User: mugglmenzel
 * Date: 22.06.13
 * Time: 11:08
 * To change this template use File | Settings | File Templates.
 */
@DynamoDBTable(tableName = "journwe-placeoption")
public class RouteOption implements IAdventureComponent {

    private String adventureId;

    @JournweCloneable
    private String placeId;

    @JournweCloneable
    private String address;

    public static RouteOption fromId(String id) {
        RouteOption po = new RouteOption();
        po.setAdventureId(id.split(":")[0]);
        po.setPlaceId(id.split(":")[1]);
        return po;
    }

    @DynamoDBIgnore
    public String getOptionId() {
        return adventureId + ":" + placeId;
    }

    @DynamoDBHashKey(attributeName = "adventureId")
    public String getAdventureId() {
        return adventureId;
    }

    public void setAdventureId(String adventureId) {
        this.adventureId = adventureId;
    }

    @DynamoDBRangeKey(attributeName = "placeId")
    @DynamoDBAutoGeneratedKey
    public String getPlaceId() {
        return placeId;
    }

    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    @DynamoDBAttribute
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
